"""Steihaug–Toint CGLS normal step for the trust-funnel barrier subproblem."""

from typing import Self, cast

import jax
from equinox import tree_at
from jax import numpy as jnp
from jax.typing import DTypeLike
from jaxtyping import Array, Bool, Float, Scalar

from ...dual import Dual
from ...linalg import steihaug_step
from ...primal import InteriorPointPrimal
from ..funnel_barrier import FunnelBarrierSubProblem
from .base import RESULTS, SubProblemSolver, SubProblemSolverState

__all__ = [
    "ScaledNormalStepState",
    "ScaledNormalStepSolver",
]


class ScaledNormalStepState(SubProblemSolverState):
    """Carry of a trust-funnel normal-step solve.

    Attributes
    ----------
    radius
        Normal trust-region radius ``δᵛ`` (scaled coordinates) used for
        this solve.
    n_cg_iter
        Cumulative CGLS iterations.
    on_boundary
        ``True`` when the returned step saturates ``δᵛ``.
    dm_v_n
        Model decrease ``Δm_v,n = m_v(0) − m_v(w_n)`` of the returned step.
    cauchy_decrease
        Decrease ``m_v(0) − m_v(w_C)`` of the Cauchy point (3.3)–(3.4); the
        returned step never does worse (eq. 3.6).
    step_norm
        ``‖w_n‖₂ = ‖P⁻¹ n‖₂``.
    unconstrained_cauchy_norm
        ``‖P⁻¹ n*‖₂`` of the unconstrained Cauchy minimiser (3.8), used by
        the radius reset (3.31).
    ftb_truncated
        ``True`` when the fraction-to-boundary rule shortened the CGLS step.
    """

    radius: Scalar
    n_cg_iter: int
    on_boundary: Bool[Array, ""]
    dm_v_n: Scalar
    cauchy_decrease: Scalar
    step_norm: Scalar
    unconstrained_cauchy_norm: Scalar
    ftb_truncated: Bool[Array, ""]

    @classmethod
    def cold(cls, radius: Scalar | float, dtype: DTypeLike = float) -> Self:
        """Zero-iteration carry with the given radius.

        Parameters
        ----------
        radius
            Normal trust-region radius ``δᵛ``.
        dtype
            Floating dtype of the scalar fields.

        Returns
        -------
        Self
            Cold state with zero counters / decreases and ``success=False``.
        """
        zero = jnp.asarray(0.0, dtype)
        return cls(
            n_iter=jnp.asarray(0, jnp.int32),
            success=jnp.asarray(False),
            status=RESULTS.successful,
            radius=jnp.asarray(radius, dtype),
            n_cg_iter=jnp.asarray(0, jnp.int32),
            on_boundary=jnp.asarray(False),
            dm_v_n=zero,
            cauchy_decrease=zero,
            step_norm=zero,
            unconstrained_cauchy_norm=zero,
            ftb_truncated=jnp.asarray(False),
        )


class ScaledNormalStepSolver(
    SubProblemSolver[
        InteriorPointPrimal, FunnelBarrierSubProblem, ScaledNormalStepState
    ]
):
    """Inexact normal step of Curtis, Gould, Robinson & Toint (2017), Sect. 3.1.

    Approximately solves, in the scaled step ``w = P⁻¹ n``,

    ```
    min_w  ½ ‖ĉ + Â w‖²₂    s.t.  ‖w‖₂ ≤ δᵛ,   w_s ≥ −(1 − κ_fbn) e
    ```

    with ``ĉ = c(x, s)`` and ``Â = J(x, s) P`` taken matrix-free from a
    :class:`~slsqp_jax.sqpdax.subproblem.funnel_barrier.FunnelBarrierSubProblem`.
    The algorithm is CGLS (conjugate gradients on the normal equations
    ``ÂᵀÂ w = −Âᵀĉ``) started from ``w = 0`` with Steihaug–Toint
    termination: CG iterate norms grow monotonically, so the first iterate
    leaving the ball is replaced by the point where the search direction
    crosses the boundary and the iteration stops. Every iterate lies in the
    Krylov space generated by ``Âᵀĉ``, hence in ``range(Âᵀ)`` (eq. 3.7).

    The returned step satisfies the paper's requirements (3.5)–(3.7):

    * ball and fraction-to-boundary constraints (3.5): the CGLS step is
      backtracked along the ray from ``0`` onto the box
      :meth:`~slsqp_jax.sqpdax.subproblem.scaled_barrier.ScaledBarrierSubProblem.primal_box`
      (ray scaling preserves both the ball and ``range(Âᵀ)``);
    * Cauchy decrease (3.6): the Cauchy point ``w_C = −α_C Âᵀĉ`` of
      (3.3)–(3.4) is computed exactly (1-D minimiser clipped by ball and
      box) and returned instead whenever the backtracked CGLS step reduces
      ``m_v`` by less.

    The dual block of the returned step is zero; the step is in *scaled*
    coordinates, like the tangential solvers, and the orchestrator unscales
    the composite step.

    Attributes
    ----------
    solver_state_class
        :class:`ScaledNormalStepState`.
    max_iter
        Maximum CGLS iterations.
    tol
        Relative tolerance on the normal-equation residual
        ``‖Âᵀ(ĉ + Âw)‖ ≤ tol · ‖Âᵀĉ‖``.
    """

    solver_state_class: type[ScaledNormalStepState] = ScaledNormalStepState

    max_iter: int = 50
    tol: float = 1e-6

    def solve(
        self,
        subproblem: FunnelBarrierSubProblem,
        x0: tuple[InteriorPointPrimal, Dual],
        initial_state: ScaledNormalStepState,
    ) -> tuple[tuple[InteriorPointPrimal, Dual], ScaledNormalStepState]:
        """Compute the scaled normal step inside ``δᵛ`` and the FTB box.

        Parameters
        ----------
        subproblem
            Funnel barrier subproblem at the current iterate.
        x0
            Unused warm start (CGLS must start from ``0`` for the
            Steihaug–Toint and range-space guarantees); kept for the
            :class:`~slsqp_jax.sqpdax.subproblem.solver.base.SubProblemSolver`
            interface.
        initial_state
            Carries ``radius`` (``δᵛ``).

        Returns
        -------
        step
            ``(scaled_normal_step, zero_dual)``.
        state
            Refreshed :class:`ScaledNormalStepState`.

        Raises
        ------
        TypeError
            If ``subproblem`` is not a ``FunnelBarrierSubProblem``.
        """
        del x0
        if not isinstance(subproblem, FunnelBarrierSubProblem):
            raise TypeError(
                "subproblem must be a FunnelBarrierSubProblem. Got "
                f"{type(subproblem)} instead."
            )
        lag = subproblem.lagrangian
        n, meq, mineq = lag.n, lag.meq, lag.mineq
        dtype = lag.ref.x.dtype
        radius = jnp.asarray(initial_state.radius, dtype)
        tiny = jnp.asarray(jnp.finfo(dtype).tiny, dtype)

        def to_primal(w: Float[Array, " w"]) -> InteriorPointPrimal:
            return InteriorPointPrimal.from_flat(w, n, mineq)

        def to_dual(y: Float[Array, " m"]) -> Dual:
            return Dual.from_flat(y, n, mineq, meq)

        def A(w: Float[Array, " w"]) -> Float[Array, " m"]:
            return subproblem.jac_mvp(to_primal(w)).flatten()

        def At(y: Float[Array, " m"]) -> Float[Array, " w"]:
            return subproblem.jac_t_mvp(to_dual(y)).flatten()

        c_hat = subproblem.dual_grad().flatten()
        v = jnp.linalg.norm(c_hat)
        lo, _hi = subproblem.primal_box()

        def model_v(w: Float[Array, " w"]) -> Scalar:
            return jnp.linalg.norm(c_hat + A(w))

        # --- Cauchy point along the scaled steepest descent −Âᵀĉ (3.3)–(3.4) ---
        d = -At(c_hat)
        pi_v = jnp.linalg.norm(d)
        Ad = A(d)
        curv = jnp.dot(Ad, Ad)
        alpha_star = jnp.where(curv > tiny, pi_v**2 / jnp.maximum(curv, tiny), 0.0)
        alpha_ball = jnp.where(pi_v > tiny, radius / jnp.maximum(pi_v, tiny), jnp.inf)
        alpha_box = alpha_star * self._box_fraction(alpha_star * d, lo)
        alpha_c = jnp.minimum(alpha_star, jnp.minimum(alpha_ball, alpha_box))
        w_c = alpha_c * d
        cauchy_decrease = v - model_v(w_c)
        unconstrained_cauchy_norm = alpha_star * pi_v

        # --- CGLS with Steihaug–Toint termination, started at w = 0 --------------
        rel_tol_sq = (jnp.asarray(self.tol, dtype) * pi_v) ** 2

        def body(_i, carry):
            w, r, s, p, gamma, done, ncg, on_bnd = carry

            def do(c):
                w, r, _s, p, gamma, _done, ncg, on_bnd = c
                q = A(p)
                qq = jnp.dot(q, q)
                alpha = jnp.where(qq > tiny, gamma / jnp.maximum(qq, tiny), 0.0)
                w_new, cross = steihaug_step(w, p, alpha, radius)
                r_new = r - alpha * q
                s_new = At(r_new)
                gamma_new = jnp.dot(s_new, s_new)
                beta = jnp.where(
                    gamma > tiny, gamma_new / jnp.maximum(gamma, tiny), 0.0
                )
                p_new = s_new + beta * p
                conv = (gamma_new <= rel_tol_sq) | (qq <= tiny)
                return (
                    w_new,
                    r_new,
                    s_new,
                    p_new,
                    gamma_new,
                    cross | conv,
                    ncg + 1,
                    on_bnd | cross,
                )

            return jax.lax.cond(done, lambda c: c, do, carry)

        w0 = jnp.zeros_like(d)
        gamma0 = pi_v**2
        init = (
            w0,
            -c_hat,
            d,
            d,
            gamma0,
            gamma0 <= rel_tol_sq,
            jnp.zeros((), jnp.int32),
            jnp.asarray(False),
        )
        w_cg, _, _, _, _, _, n_cg, _ = jax.lax.fori_loop(0, self.max_iter, body, init)

        # --- fraction-to-boundary backtrack along the ray, Cauchy fallback (3.6) ---
        beta_ftb = self._box_fraction(w_cg, lo)
        w_bt = beta_ftb * w_cg
        dm_cg = v - model_v(w_bt)
        use_cauchy = dm_cg < cauchy_decrease
        w = jnp.where(use_cauchy, w_c, w_bt)
        dm_v_n = jnp.where(use_cauchy, cauchy_decrease, dm_cg)
        step_norm = jnp.linalg.norm(w)
        on_boundary = step_norm >= radius * (1.0 - 1e-6)
        ftb_truncated = beta_ftb < 1.0
        finite = jnp.all(jnp.isfinite(w)) & jnp.isfinite(dm_v_n)
        status = RESULTS.where(finite, RESULTS.successful, RESULTS.singular)

        self.logger.debug(
            "normal step: radius={radius:.3e} pi_v={pi_v:.3e} cg_iters={cg_iters} "
            "dm_v={dm:.3e} cauchy={cauchy:.3e} ftb_beta={beta:.3f} "
            "cauchy_fallback={fallback} on_boundary={on_boundary}",
            radius=radius,
            pi_v=pi_v,
            cg_iters=n_cg,
            dm=dm_v_n,
            cauchy=cauchy_decrease,
            beta=beta_ftb,
            fallback=use_cauchy,
            on_boundary=on_boundary,
        )
        self.logger.warning(
            "normal step is non-finite (status={status})",
            when=~finite,
            status=status,
        )

        step = (to_primal(w), cast(Dual, jax.tree.map(jnp.zeros_like, lag.dual)))
        new_state = cast(
            ScaledNormalStepState,
            tree_at(
                lambda st: (
                    st.n_iter,
                    st.success,
                    st.status,
                    st.radius,
                    st.n_cg_iter,
                    st.on_boundary,
                    st.dm_v_n,
                    st.cauchy_decrease,
                    st.step_norm,
                    st.unconstrained_cauchy_norm,
                    st.ftb_truncated,
                ),
                initial_state,
                (
                    initial_state.n_iter + 1,
                    finite,
                    status,
                    radius,
                    initial_state.n_cg_iter + n_cg,
                    on_boundary,
                    dm_v_n,
                    cauchy_decrease,
                    step_norm,
                    unconstrained_cauchy_norm,
                    ftb_truncated,
                ),
            ),
        )
        return step, new_state

    @staticmethod
    def _box_fraction(w: Float[Array, " w"], lo: Float[Array, " w"]) -> Scalar:
        """Largest ``β ∈ [0, 1]`` with ``β w ≥ lo`` componentwise.

        Parameters
        ----------
        w
            Candidate scaled step.
        lo
            Lower faces of the box (``−inf`` on free coordinates).

        Returns
        -------
        Scalar
            Backtracking factor; ``1`` when ``w`` already lies in the box.
        """
        binding = (w < 0.0) & jnp.isfinite(lo)
        safe_w = jnp.where(binding, w, -1.0)
        ratios = jnp.where(binding, lo / safe_w, jnp.inf)
        return jnp.minimum(jnp.asarray(1.0, w.dtype), jnp.min(ratios, initial=jnp.inf))
